language: node_js
node_js:
  - '8'
install:
- npm install -g truffle
- npm install -g ganache-cli
- npm install
script:
  - npm test

after_success:
  - npm run coverage && cat coverage/lcov.info | coveralls
