language: node_js
node_js:
  - '8'
install:
- npm install -g truffle
- npm install -g ganache-cli
- npm install
script:
  - ganache-cli > /dev/null &
  - sleep 5
  - npm test


after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
